### ISSUE TITLE
Missing small statics

### ISSUE THREAD

**Issue by onekiloparsec** [eon01/PainlessDocker#1]
Just starting course and ... missing some statics. Not a big deal. But rather annoying.

<img width="341" alt="screen shot 2018-08-24 at 16 05 16" src="https://user-images.githubusercontent.com/226224/44588975-83fc3d80-a7b7-11e8-94c3-595bdbe89f2d.png">

**Comment by eon01** [comment]
Hi Cédri, thank you for submitting this. I just fixed it :-)
